// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2HMn9EIgLjC8rrXPKXbsRSDsMUPDcVc8',
    appId: '1:1025614045714:web:7f945e0324e8321dd36ecb',
    messagingSenderId: '1025614045714',
    projectId: 'esalesperson-9b2c9',
    authDomain: 'esalesperson-9b2c9.firebaseapp.com',
    storageBucket: 'esalesperson-9b2c9.appspot.com',
    measurementId: 'G-5T96W8SFRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKuZXnjGMgdXYt-CMcGkoczatMitE2Ekw',
    appId: '1:1025614045714:android:656b4ccad40db8c8d36ecb',
    messagingSenderId: '1025614045714',
    projectId: 'esalesperson-9b2c9',
    storageBucket: 'esalesperson-9b2c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvmoSXMl0vO4sjg35TPQ-_pBi2iX8rWeo',
    appId: '1:1025614045714:ios:a673015ebd882503d36ecb',
    messagingSenderId: '1025614045714',
    projectId: 'esalesperson-9b2c9',
    storageBucket: 'esalesperson-9b2c9.appspot.com',
    iosBundleId: 'com.example.eSellsperson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvmoSXMl0vO4sjg35TPQ-_pBi2iX8rWeo',
    appId: '1:1025614045714:ios:c1532799eef03ff8d36ecb',
    messagingSenderId: '1025614045714',
    projectId: 'esalesperson-9b2c9',
    storageBucket: 'esalesperson-9b2c9.appspot.com',
    iosBundleId: 'com.example.eSellsperson.RunnerTests',
  );
}
